from langchain_core.output_parsers import PydanticOutputParser, StrOutputParser
from models.models import SearchQueryList, ModuleList, SubmoduleList, EnhancedModuleList, TopicAnalysis, ModulePlanning

search_queries_parser = PydanticOutputParser(pydantic_object=SearchQueryList)
modules_parser = PydanticOutputParser(pydantic_object=ModuleList)
module_queries_parser = PydanticOutputParser(pydantic_object=SearchQueryList)
submodule_parser = PydanticOutputParser(pydantic_object=SubmoduleList)
topic_analysis_parser = PydanticOutputParser(pydantic_object=TopicAnalysis)
module_planning_parser = PydanticOutputParser(pydantic_object=ModulePlanning)
enhanced_modules_parser = PydanticOutputParser(pydantic_object=EnhancedModuleList)
