"""\Add credits column and constraint to User model\

Revision ID: 9b335ab9fb70
Revises: cbb1331fc179
Create Date: 2025-04-08 18:10:56.021833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b335ab9fb70'
down_revision = 'cbb1331fc179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_learning_path_user_date', 'learning_paths', ['user_id', sa.literal_column('creation_date DESC')], unique=False)
    op.create_index('idx_learning_path_user_fav_date', 'learning_paths', ['user_id', 'favorite', sa.literal_column('creation_date DESC')], unique=False)
    op.create_index('idx_learning_path_user_favorite', 'learning_paths', ['user_id', 'favorite'], unique=False)
    op.create_index('idx_learning_path_user_modified', 'learning_paths', ['user_id', sa.literal_column('last_modified_date DESC')], unique=False)
    op.create_index('idx_learning_path_user_source', 'learning_paths', ['user_id', 'source'], unique=False)
    op.add_column('users', sa.Column('credits', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_index('idx_learning_path_user_source', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_modified', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_favorite', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_fav_date', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_date', table_name='learning_paths')
    # ### end Alembic commands ### 