"""initial_schema_reflecting_production

Revision ID: bace8ae61775
Revises: 
Create Date: 2025-04-30 21:22:26.678417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bace8ae61775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_transactions', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_credit_transaction_action_type', 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_credit_transaction_admin_id', 'credit_transactions', ['admin_user_id'], unique=False)
    op.create_index('idx_credit_transaction_created_at', 'credit_transactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_credit_transaction_user_id', 'credit_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_admin_user_id'), 'credit_transactions', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_stripe_checkout_session_id'), 'credit_transactions', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), 'credit_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'credit_transactions', 'users', ['admin_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_generation_task_created_at', table_name='generation_tasks')
    op.create_index('idx_generation_task_created_at', 'generation_tasks', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_generation_tasks_created_at'), 'generation_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_tasks_history_entry_id'), 'generation_tasks', ['history_entry_id'], unique=False)
    op.create_index(op.f('ix_generation_tasks_user_id'), 'generation_tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'generation_tasks', 'learning_paths', ['history_entry_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'generation_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_user_path_submodule', table_name='learning_path_progress')
    op.create_unique_constraint('uq_user_path_submodule', 'learning_path_progress', ['user_id', 'learning_path_id', 'module_index', 'submodule_index'])
    op.alter_column('learning_paths', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('learning_paths', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='ISO 639-1 language code for the course content',
               existing_nullable=False)
    op.create_index('idx_learning_path_path_id', 'learning_paths', ['path_id'], unique=False)
    op.create_index('idx_learning_path_topic', 'learning_paths', ['topic'], unique=False)
    op.create_index('idx_learning_path_user_date', 'learning_paths', ['user_id', sa.literal_column('creation_date DESC')], unique=False)
    op.create_index('idx_learning_path_user_fav_date', 'learning_paths', ['user_id', 'favorite', sa.literal_column('creation_date DESC')], unique=False)
    op.create_index('idx_learning_path_user_favorite', 'learning_paths', ['user_id', 'favorite'], unique=False)
    op.create_index('idx_learning_path_user_id', 'learning_paths', ['user_id'], unique=False)
    op.create_index('idx_learning_path_user_modified', 'learning_paths', ['user_id', sa.literal_column('last_modified_date DESC')], unique=False)
    op.create_index('idx_learning_path_user_source', 'learning_paths', ['user_id', 'source'], unique=False)
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_learning_paths_language'), 'learning_paths', ['language'], unique=False)
    op.create_index(op.f('ix_learning_paths_path_id'), 'learning_paths', ['path_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_topic'), 'learning_paths', ['topic'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_foreign_key(None, 'learning_paths', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sessions', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_session_token', 'sessions', ['refresh_token'], unique=False)
    op.create_index('idx_session_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index('ix_sessions_refresh_token', 'sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password_reset_token_hash'), 'users', ['password_reset_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_refresh_token', table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index('idx_session_user_id', table_name='sessions')
    op.drop_index('idx_session_token', table_name='sessions')
    op.alter_column('sessions', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'learning_paths', type_='foreignkey')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_topic'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_path_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_language'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_index('idx_learning_path_user_source', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_modified', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_id', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_favorite', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_fav_date', table_name='learning_paths')
    op.drop_index('idx_learning_path_user_date', table_name='learning_paths')
    op.drop_index('idx_learning_path_topic', table_name='learning_paths')
    op.drop_index('idx_learning_path_path_id', table_name='learning_paths')
    op.alter_column('learning_paths', 'language',
               existing_type=sa.VARCHAR(length=10),
               comment='ISO 639-1 language code for the course content',
               existing_nullable=False)
    op.alter_column('learning_paths', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('uq_user_path_submodule', 'learning_path_progress', type_='unique')
    op.create_index('uq_user_path_submodule', 'learning_path_progress', ['user_id', 'learning_path_id', 'module_index', 'submodule_index'], unique=True)
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.drop_constraint(None, 'generation_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_generation_tasks_user_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_history_entry_id'), table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_created_at'), table_name='generation_tasks')
    op.drop_index('idx_generation_task_created_at', table_name='generation_tasks')
    op.create_index('idx_generation_task_created_at', 'generation_tasks', ['created_at'], unique=False)
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_stripe_payment_intent_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_stripe_checkout_session_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_admin_user_id'), table_name='credit_transactions')
    op.drop_index('idx_credit_transaction_user_id', table_name='credit_transactions')
    op.drop_index('idx_credit_transaction_created_at', table_name='credit_transactions')
    op.drop_index('idx_credit_transaction_admin_id', table_name='credit_transactions')
    op.drop_index('idx_credit_transaction_action_type', table_name='credit_transactions')
    op.alter_column('credit_transactions', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ### 