"""Add server_default to users.created_at and align others

Revision ID: manual_add_created_at_default
Revises: cbb1331fc179 # Adjust 'Revises' ID to the LATEST existing migration ID
Create Date: 2024-08-10 12:00:00.000000 # Approximate date

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'manual_add_created_at_default' 
# IMPORTANT: Update this ID to the actual latest migration revision ID from the versions folder
down_revision: Union[str, None] = 'cbb1331fc179' 
brach_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users',
        'created_at',
        existing_type=sa.TIMESTAMP(),
        nullable=False,
        server_default=sa.func.now() # Add the server default
        )
    # Note: Autogenerate might have also tried to alter credits and is_email_verified
    # but since we confirmed they already have server defaults in the DB, 
    # we only need to alter created_at.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users',
        'created_at',
        existing_type=sa.TIMESTAMP(),
        nullable=False, # Keep nullable=False as per original state before this migration
        server_default=None # Remove the server default
        )
    # ### end Alembic commands ### 